# Generated by Django 5.2 on 2025-05-01 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='users/')),
                ('data_added', models.DateField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('AD', 'ADMIN'), ('BY', 'BUYER'), ('SE', 'SELLER')], max_length=2)),
            ],
        ),
    ]
