# Generated by Django 5.2 on 2025-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field=200, upload_to='products/', width_field=200)),
                ('price', models.IntegerField()),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
